name: Docker Image CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Frontend Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-image:frontend -f ./docker/frontend/Dockerfile .

      - name: Build Backend Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-image:backend -f ./docker/backend/Dockerfile .

      - name: Push Frontend Image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-image:frontend

      - name: Push Backend Image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-image:backend

